---
dependency:
  name: galaxy

driver:
  name: docker
  safe_files:
    - nexus-downloads

lint:
  name: yamllint

platforms:

  - name: nexus3-oss-debian-stretch
    image: thoteam/ansible-debian_stretch-apache-java
    image_version: latest
    command: /lib/systemd/systemd
    privileged: true
    ports:
      - 8092:443
    groups:
      - nexus

  - name: ldap-server-mock
    image: thoteam/ldap-server-mock
    image_version: latest
    ports:
      - 3004
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/ldap-server-mock-conf.json:/srv/ldap-server-mock-conf.json
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/ldap-server-mock-users.json:/srv/ldap-server-mock-users.json
    groups:
      - mockldap

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default-debian_stretch
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - check
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
