---

sudo: required
language: python
cache:
  pip: true
  directories:
    - molecule/default/.molecule
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - ./tests/test_molecule.sh
