---

sudo: required
language: python
python:
  - 2.7
  - 3.5
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo apt-get -y install groovy
install:
  - pip install -r requirements.txt
script:
  - ./tests/run_all_tests.sh
