---

# @deprecated: nexus_package must not exists
# @version: 2.2.0
- name: Broken compatibility => nexus_package is now dynamically calculated
  fail:
    msg: >-
      You have set the variable nexus_package in your playbook.
      Starting from version 2.2.0 of this role, this is not compatible
      with the new nexus latest version detection feature and is not
      supported anymore. Please use the nexus_version variable only.
  when: nexus_package is defined
