---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ubuntu-16.04
    image: thoteam/ansible-ubuntu16.04-apache-java
    image_version: latest
    command: /lib/systemd/systemd
    privileged: true
  - name: centos-7
    image: thoteam/ansible-centos7-apache-java
    image_version: latest
    command: /lib/systemd/systemd
    privileged: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False

scenario:
  name: default
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - converge
    - lint
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
