---
dependency:
  name: galaxy

driver:
  name: docker
  safe_files:
    - nexus-downloads

lint:
  name: yamllint

platforms:
  - name: nexus3-oss-default
    image: thoteam/ansible-centos7-apache-java
    image_version: latest
    command: /usr/sbin/init
    privileged: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  test_sequence:
    - lint

verifier:
  name: testinfra
  lint:
    name: flake8
