---
- name: Converge
  hosts: all
  pre_tasks:
    - name: configure default ssl key and cert based on OS
      include_vars: "../ssl-{{ ansible_os_family }}.yml"
  roles:
    - role: nexus3-oss
  vars:
    httpd_setup_enable: true
    httpd_copy_ssl_files: false
    httpd_ssl_cert_file_location: "{{ default_cert }}"
    httpd_ssl_cert_key_location: "{{ default_key }}"
    public_hostname: localhost
    nexus_backup_configure: true

    nexus_config_yum: true
    nexus_repos_yum_proxy:
      - name: epel_centos_7_x86_64
        remote_url: http://download.fedoraproject.org/pub/epel/7/x86_64

    nexus_scheduled_tasks:
      #  Example task to purge maven snapshots
      - name: Purge-maven-snapshots
        cron: '0 50 23 * * ?'
        typeId: repository.maven.remove-snapshots
        task_alert_email: alerts@example.org  # optional
        taskProperties:
          repositoryName: "*"
          minimumRetained: "2"
          snapshotRetentionDays: "2"
          gracePeriodInDays: "2"
        booleanTaskProperties:
          removeIfReleased: true
