---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - name: configure default ssl key and cert based on OS
      include_vars: "../ssl-{{ ansible_os_family }}.yml"
  roles:
    - role: nexus3-oss
  vars:
    httpd_setup_enable: true
    httpd_copy_ssl_files: false
    httpd_ssl_cert_file_location: "{{ default_cert }}"
    httpd_ssl_cert_key_location: "{{ default_key }}"

    nexus_anonymous_access: true
    nexus_config_npm: true
    nexus_repos_npm_hosted: []
    nexus_repos_npm_group:
      - name: npm-public
        member_repos:
          - npm-registry
    nexus_repos_npm_proxy:
      - name: npm-registry
        remote_url: https://registry.npmjs.org/

    nexus_backup_configure: true
